import Head from "next/head";
import type { PropsWithChildren } from "react";
import Header from "./header";
import Aside from "./aside";

const MainLayout = ({ children }: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Calendify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Aside />
      <main className="mx-auto max-w-7xl">
        <div className="px-3 md:ml-56 md:px-5">{children}</div>
      </main>
    </>
  );
};

export default MainLayout;